# Generated by Django 2.1 on 2020-05-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
